///////////////////////////////////////////////////////////////
// Channelclient.cs - WCF Calculator Service client          //
//                                                           //
// Jim Fawcett, CSE775 - Distributed Objects, Spring 2008    //
///////////////////////////////////////////////////////////////
/*
 * Based on Microsoft WCF Samples
 * http://msdn2.microsoft.com/en-us/library/ms751514.aspx
 * 
 * Note:
 *   Uses Programmatic configuration, no app.config file used.
 *   Still uses proxy generated by SvcUtil.exe
 *   
 */

using System;
using System.ServiceModel;
using System.ServiceModel.Channels;

namespace Calculator
{
  class Client
  {
    static void Main()
    {
      Console.Write("\n  Calculator Service Channel Factory Client");
      Console.Write("\n ===========================================\n");

      // Create a channel
      EndpointAddress address 
        = new EndpointAddress("http://localhost:8000/Calculator/service");
      WSHttpBinding binding = new WSHttpBinding();
      ChannelFactory<ICalculator> factory 
        = new ChannelFactory<ICalculator>(binding, address);
      ICalculator channel = factory.CreateChannel();

      // Call the Add service operation.
      double value1 = 100.00D;
      double value2 = 15.99D;
      double result = channel.Add(value1, value2);
      Console.Write("\n  Add({0},{1}) = {2}", value1, value2, result);

      // Call the Subtract service operation.
      value1 = 145.00D;
      value2 = 76.54D;
      result = channel.Subtract(value1, value2);
      Console.Write("\n  Subtract({0},{1}) = {2}", value1, value2, result);

      // Call the Multiply service operation.
      value1 = 9.00D;
      value2 = 81.25D;
      result = channel.Multiply(value1, value2);
      Console.Write("\n  Multiply({0},{1}) = {2}", value1, value2, result);

      // Call the Divide service operation.
      value1 = 22.00D;
      value2 = 7.00D;
      result = channel.Divide(value1, value2);
      Console.Write("\n  Divide({0},{1}) = {2}", value1, value2, result);

      Console.Write("\n\n  Press ENTER to terminate client");
      Console.Read();

      ((IChannel)channel).Close();
    }
  }
}
